flowchart TD
    A((Начало)) --> B[/"Получение a, b, n"/]
    B --> C["Вычисление h = (b-a)/n"]
    C --> D[Инициализация sum = 0, i = 1]
    D --> F{{i <= n}}
    F -->|false| J[Результат = h * sum]
    F -->|true| G[x = a + i*h]
    G --> H["sum += f(x)"]
    H --> I[i++]
    I --> F
    J --> K[/Возврат результата/]
    K --> L((Конец))
