package com.arekalov.compmatlab3.common

const val MADE_BY_STR = "Made by arekalov"
const val SOURCE_CODE_STR = "Source code here"
const val CHANGE_THEME_STR = "Change theme"

const val UNEXPECTED_STR = "unexpected"
const val SINGLE_STR = "single"
const val SYSTEM_STR = "system"
const val INPUT_SPECS_STR = "Enter function data:"
const val ENTER_A_STR = "Enter double a"
const val ENTER_B_STR = "Enter double b"
const val ENTER_X_STR = "Enter double x"
const val ENTER_Y_STR = "Enter double y"
const val EQUATION_STR = "Equation"
const val A_LABEL_STR = "a:"
const val B_LABEL_STR = "b:"
const val X_LABEL_STR = "x:"
const val Y_LABEL_STR = "y:"
const val METHOD_LABEL_STR = "Method:"
const val SOLVE_BUTTON = "Solve"
