flowchart TD
    A((Начало)) --> B[/Ввод a, b, n/]
    B --> C["Вычисление h = (b-a)\n"]
    C --> D["Инициализация sum = (f(a) + f(b))\/2"]
    D --> E[Инициализация i = 1]
    E --> F{i < n}
    F -->|true| G[Вычисление x = a + i*h]
    G --> H["sum += f(x)"]
    H --> I[i++]
    I --> F
    F -->|false| J[Результат = h * sum]
    J --> K[/Возврат результата/]
    K --> L((Конец))
